### ISSUE TITLE
Not working with SMTP driver

### ISSUE THREAD

**Issue by DougSisk** [spinen/laravel-mail-assertions#27]
I cannot use any of the assertions while on the SMTP driver. They work if I switch over to the log driver.

**Comment by jimmypuckett** [comment]
Ya, that is how it hooks into the system to "read" the email.  Thanks for pointing out that it was not clear in the documentation.  We will add some clarification to the README.

Thanks!

**Comment by DougSisk** [comment]
Ahh… I see! Thanks for the clarification.

**Comment by ssfinney** [comment]
I just merged an addition to the readme for this. Thanks!
