### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by mits87** [spinen/laravel-mail-assertions#34]
Hi,

I have problem with install your package.

Your requirements could not be resolved to an installable set of packages.

>   Problem 1
>     - Installation request for spinen/laravel-mail-assertions ^0.3.0 -> satisfiable by spinen/laravel-mail-assertions[0.3.0].
>     - Conclusion: remove swiftmailer/swiftmailer v6.0.1
>     - Conclusion: don't install swiftmailer/swiftmailer v6.0.1
>     - spinen/laravel-mail-assertions 0.3.0 requires swiftmailer/swiftmailer ~5.1 -> satisfiable by swiftmailer/swiftmailer[v5.1.0, v5.2.0, v5.2.1, v5.2.2, v5.3.0, v5.3.1, v5.4.0, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8].
>     - Can only install one of: swiftmailer/swiftmailer[v5.1.0, v6.0.1].
>     - Can only install one of: swiftmailer/swiftmailer[v5.2.0, v6.0.1].
>     - Can only install one of: swiftmailer/swiftmailer[v5.2.1, v6.0.1].
>     - Can only install one of: swiftmailer/swiftmailer[v5.2.2, v6.0.1].
>     - Can only install one of: swiftmailer/swiftmailer[v5.3.0, v6.0.1].
>     - Can only install one of: swiftmailer/swiftmailer[v5.3.1, v6.0.1].
>     - Can only install one of: swiftmailer/swiftmailer[v5.4.0, v6.0.1].
>     - Can only install one of: swiftmailer/swiftmailer[v5.4.1, v6.0.1].
>     - Can only install one of: swiftmailer/swiftmailer[v5.4.2, v6.0.1].
>     - Can only install one of: swiftmailer/swiftmailer[v5.4.3, v6.0.1].
>     - Can only install one of: swiftmailer/swiftmailer[v5.4.4, v6.0.1].
>     - Can only install one of: swiftmailer/swiftmailer[v5.4.5, v6.0.1].
>     - Can only install one of: swiftmailer/swiftmailer[v5.4.6, v6.0.1].
>     - Can only install one of: swiftmailer/swiftmailer[v5.4.7, v6.0.1].
>     - Can only install one of: swiftmailer/swiftmailer[v5.4.8, v6.0.1].
>     - Installation request for swiftmailer/swiftmailer (locked at v6.0.1) -> satisfiable by swiftmailer/swiftmailer[v6.0.1].
> 

Could you fix it?
Thx

**Comment by ssfinney** [comment]
Hi @mits87! This is happening because Laravel 5.5 now requires Swiftmailer 6, and our composer.json was locked to version 5.

#35 will resolve this. Thanks for reporting this to us!

**Comment by jimmypuckett** [comment]
@ssfinney, once the builds pass I will merge it. I'm about to be traveling, so will you be able to tag it?

**Comment by ssfinney** [comment]
@jimmypuckett Sure I can do that

**Comment by ssfinney** [comment]
@mits87 Version `0.3.1` now fixes this issue.

**Comment by mits87** [comment]
It is working now thanks!
