### ISSUE TITLE
Problem with this mail assertion plugin

### ISSUE THREAD

**Issue by akash-dangal** [spinen/laravel-mail-assertions#37]
I did run : `composer require spinen/laravel-mail-assertions` then implemented my custom test code making reference to your example code. However, I got an error 
```
RuntimeException: A facade root has not been set.

Root\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:218
Root\vendor\spinen\laravel-mail-assertions\src\MailTracking.php:51

```
When I try to solve it by adding , `Spinen\MailAssertions\MailTracking;` to `config/app.php` `providers array`  I got error, and that won't help either.

Can you suggest me what I am missing here please, and how can I make it work.

**Comment by ssfinney** [comment]
Hi @akash-dangal!

This issue has been found already. Please see #36 for updates.
