### ISSUE TITLE
Would be possible to check many emails?

### ISSUE THREAD

**Issue by neoplomero** [spinen/laravel-mail-assertions#40]
At the moment if more than one take last but this leaves a hole if your sending at least 2

**Comment by ssfinney** [comment]
Hey @neoplomero. Do you mean passing an array of emails to check? Are you trying to test them all at one time, with the same assertions on each?

**Comment by ssfinney** [comment]
@neoplomero Are you still interested in this enhancement? I'm going to close this issue, but please reply back if you still have questions.
