### ISSUE TITLE
Upgrade to Laravel 5.7.* from 5.6.*

### ISSUE THREAD

**Issue by MehulBawadia** [spinen/laravel-mail-assertions#45]
I am using this package in my Laravel 5.6.* application and I want to upgrade to Laravel 5.7.*.. 

Since this package doesn't have any support for Laravel 5.7.* as of today, I am unable to upgrade my application.

So, my question is when will this package be getting upgraded to Laravel 5.7.* ?

**Comment by mr-feek** [comment]
https://github.com/spinen/laravel-mail-assertions/pull/50

**Comment by ssfinney** [comment]
Hi there! We are upgrading to 5.8 now. See #51. Thanks!

**Comment by ssfinney** [comment]
Closing since we're on 5.8, and about to update the package for 6.0
